# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(348, 230)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.input_replace = QtWidgets.QComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(9)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_replace.sizePolicy().hasHeightForWidth())
        self.input_replace.setSizePolicy(sizePolicy)
        self.input_replace.setEditable(True)
        self.input_replace.setObjectName("input_replace")
        self.gridLayout.addWidget(self.input_replace, 1, 1, 1, 1)
        self.label_replace = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_replace.setFont(font)
        self.label_replace.setObjectName("label_replace")
        self.gridLayout.addWidget(self.label_replace, 1, 0, 1, 1)
        self.label_find = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_find.setFont(font)
        self.label_find.setObjectName("label_find")
        self.gridLayout.addWidget(self.label_find, 0, 0, 1, 1)
        self.is_case = QtWidgets.QCheckBox(Dialog)
        self.is_case.setObjectName("is_case")
        self.gridLayout.addWidget(self.is_case, 2, 1, 1, 1)
        self.input_find = QtWidgets.QComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(9)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_find.sizePolicy().hasHeightForWidth())
        self.input_find.setSizePolicy(sizePolicy)
        self.input_find.setEditable(True)
        self.input_find.setObjectName("input_find")
        self.gridLayout.addWidget(self.input_find, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.output_tags = QtWidgets.QLineEdit(Dialog)
        self.output_tags.setFocusPolicy(QtCore.Qt.NoFocus)
        self.output_tags.setReadOnly(True)
        self.output_tags.setObjectName("output_tags")
        self.gridLayout_2.addWidget(self.output_tags, 2, 1, 1, 1)
        self.label_old = QtWidgets.QLabel(Dialog)
        self.label_old.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_old.sizePolicy().hasHeightForWidth())
        self.label_old.setSizePolicy(sizePolicy)
        self.label_old.setMinimumSize(QtCore.QSize(65, 0))
        self.label_old.setObjectName("label_old")
        self.gridLayout_2.addWidget(self.label_old, 1, 0, 1, 1)
        self.label_preview = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_preview.setFont(font)
        self.label_preview.setAlignment(QtCore.Qt.AlignCenter)
        self.label_preview.setObjectName("label_preview")
        self.gridLayout_2.addWidget(self.label_preview, 0, 1, 1, 1)
        self.label_new = QtWidgets.QLabel(Dialog)
        self.label_new.setObjectName("label_new")
        self.gridLayout_2.addWidget(self.label_new, 2, 0, 1, 1)
        self.input_tags = TagEdit(Dialog)
        self.input_tags.setObjectName("input_tags")
        self.gridLayout_2.addWidget(self.input_tags, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Help|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.input_find, self.input_replace)
        Dialog.setTabOrder(self.input_replace, self.is_case)
        Dialog.setTabOrder(self.is_case, self.input_tags)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Find and Replace Tags"))
        self.label_replace.setText(_translate("Dialog", "Replace with:"))
        self.label_find.setText(_translate("Dialog", "Find:"))
        self.is_case.setText(_translate("Dialog", "Case sensitive matching"))
        self.label_old.setText(_translate("Dialog", "Old tags:"))
        self.label_preview.setText(_translate("Dialog", "Preview"))
        self.label_new.setText(_translate("Dialog", "New tags:"))

from aqt.tagedit import TagEdit

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

