#!/bin/sh

path=$(find /sys/class/backlight -maxdepth 1 -type l | head -n1)
b=$(cat "$path/brightness")
maxb=$(cat "$path/max_brightness")
step=$(echo "$maxb / 100" | bc)

p=$( echo "$b / $step" | bc )
p=$(( ((p + 5) / 10) * 10 ))

if [ "$1" = "up" ]; then
    p=$(( p + 10 ))
    [ $p -ge 100 ] && p=100
elif [ "$1" = "down" ]; then
    p=$(( p - 10 ))
    [ $p -le 0 ] && p=0
else
    echo "Invalid argument. Use 'up' or 'down'"
    exit 1
fi

b=$(printf "%0.f" $(echo "$p * $step" | bc))

echo $b > "$path/brightness"

icon='brightnesssettings'

notify-send -a "brightness" -i "$icon" -h int:value:$p "$p%"

