[font]
size = 11

[font.normal]
family = "terminal"

[window]
dimensions = { columns = 80, lines = 24 }
dynamic_title = true
padding = { x = 2, y = 2 }

[colors.primary]
foreground = "#ffffff"
background = "#000000"

[keyboard]
bindings = [
   { key = "C", mods = "Control|Alt", action = "Copy" },
   { key = "V", mods = "Control|Alt", action = "Paste" }
]

